const SUPABASE_URL='https://cretvvkajdrqyvpzhujj.supabase.co';
const SUPABASE_PUBLISHABLE_KEY='sb_publishable_oisKn7ncTp9TYrc27BPBjA_PdkI2oID';
const $=id=>document.getElementById(id);let allEvents=[];
const headers={apikey:SUPABASE_PUBLISHABLE_KEY,Authorization:`Bearer ${SUPABASE_PUBLISHABLE_KEY}`};
function escapeHtml(value){const div=document.createElement('div');div.textContent=String(value??'');return div.innerHTML}
function indicator(id,ok,label){const el=$(id);el.className=`indicator ${ok?'ok':'bad'}`;el.textContent=label}
function metric(id,value){$(id).textContent=value}
async function query(path){const response=await fetch(`${SUPABASE_URL}/rest/v1/${path}`,{headers});if(!response.ok)throw new Error(`Supabase ${response.status}: ${await response.text()}`);return response.json()}
function renderStatus(status){const summary=status?.summary||{};metric('kpi-people',summary.total||0);metric('kpi-compliant',summary.compliant||0);metric('kpi-helmet',summary.helmet_missing||0);metric('kpi-vest',summary.vest_missing||0);metric('kpi-both',summary.both_missing||0);metric('kpi-rate',`${Number(summary.compliance_rate||0).toFixed(1)}%`);metric('kpi-fps',Number(status?.fps||0).toFixed(1));const updated=status?new Date(status.updated_at):null;const fresh=updated&&Date.now()-updated.getTime()<15000;indicator('camera-indicator',Boolean(fresh&&status.camera_connected),'Edge camera');indicator('arduino-indicator',Boolean(fresh&&status.arduino?.connected),'Arduino');$('freshness').textContent=fresh?'LIVE':'OFFLINE';$('freshness').className=`freshness ${fresh?'live':''}`;$('edge-message').textContent=fresh?'Receiving current Edge telemetry':'Waiting for a fresh Edge update';$('camera-source').textContent=status?.camera||'—';$('last-update').textContent=updated?updated.toLocaleString():'Never';const overall=status?.overall||{state:'OFF',message:'No current Edge status'};$('overall-panel').dataset.state=overall.state;$('overall-status').textContent=overall.state;$('overall-message').textContent=overall.message||'No current Edge status';const arduino=status?.arduino||{};$('led-state').textContent=fresh?(arduino.led_state||'OFF'):'OFF';$('led-port').textContent=fresh&&arduino.connected?`Connected · ${arduino.port||'serial'}`:'Not connected';$('led-lamp').className=`lamp ${(fresh?(arduino.led_state||'OFF'):'OFF').toLowerCase()}`;const people=status?.people||[];$('people-list').innerHTML=people.length?people.map(p=>`<div class="person-row ${p.color||'pending'}"><div><strong>Person ${escapeHtml(p.tracking_id)} — ${escapeHtml(p.label)}</strong><br><span>${escapeHtml(p.reason)}</span></div><span>${Math.round(Number(p.confidence||0)*100)}%</span></div>`).join(''):'<p class="empty">No tracked people</p>'}
function renderEvents(events){$('events-body').innerHTML=events.map(e=>`<tr><td>${new Date(e.timestamp).toLocaleString()}</td><td>${escapeHtml(e.tracking_id)}</td><td>${e.helmet_worn?'Worn':'Missing'}</td><td>${e.vest_worn?'Worn':'Missing'}</td><td><span class="status-pill ${e.status.toLowerCase().replaceAll(' ','-')}">${escapeHtml(e.status)}</span></td><td>${Number(e.confidence).toFixed(2)}</td><td>${escapeHtml(e.camera)}</td></tr>`).join('')||'<tr><td colspan="7">No matching events</td></tr>'}
function analytics(events){const today=new Date();today.setHours(0,0,0,0);const todays=events.filter(e=>new Date(e.timestamp)>=today),violations=todays.filter(e=>e.status!=='COMPLIANT');metric('kpi-violations',violations.length);const byType={};violations.forEach(e=>byType[e.reason]=(byType[e.reason]||0)+1);const hourly={};todays.forEach(e=>{const h=new Date(e.timestamp).getHours().toString().padStart(2,'0');hourly[h]||={compliant:0,non_compliant:0};hourly[h][e.status==='COMPLIANT'?'compliant':'non_compliant']++});const timeline=[...todays].reverse().map((e,i,array)=>({rate:100*array.slice(0,i+1).filter(x=>x.status==='COMPLIANT').length/(i+1)}));lineChart(timeline);barChart('violation-chart',Object.entries(byType).map(([reason,count])=>({reason,count})),['count'],['#ff4d5e']);barChart('hourly-chart',Object.values(hourly),['compliant','non_compliant'],['#21c77a','#2997ff'])}
function canvas(id){const c=$(id),dpr=window.devicePixelRatio||1,w=c.clientWidth,h=c.clientHeight;c.width=w*dpr;c.height=h*dpr;const x=c.getContext('2d');x.scale(dpr,dpr);x.clearRect(0,0,w,h);return{x,w,h}}
function base(ctx){const{x,w,h}=ctx;x.strokeStyle='#243548';x.lineWidth=1;for(let i=1;i<4;i++){x.beginPath();x.moveTo(0,h*i/4);x.lineTo(w,h*i/4);x.stroke()}}
function lineChart(items){const c=canvas('rate-chart');base(c);if(!items.length)return;const{x,w,h}=c;x.strokeStyle='#21c77a';x.lineWidth=2;x.beginPath();items.forEach((v,i)=>{const px=i*w/Math.max(1,items.length-1),py=h-(Number(v.rate)/100)*(h-8)-4;i?x.lineTo(px,py):x.moveTo(px,py)});x.stroke()}
function barChart(id,items,keys,colors){const c=canvas(id);base(c);if(!items.length)return;const{x,w,h}=c,max=Math.max(1,...items.flatMap(i=>keys.map(k=>Number(i[k]||0))));const group=w/items.length;items.forEach((item,i)=>keys.forEach((key,j)=>{x.fillStyle=colors[j];const bw=Math.max(4,group/(keys.length+1)),bh=Number(item[key]||0)/max*(h-20);x.fillRect(i*group+j*bw+4,h-bh,bw-2,bh)}))}
async function refresh(){try{const [statuses,events]=await Promise.all([query('ppe_monitor_status?select=*&order=updated_at.desc&limit=1'),query('ppe_events?select=*&order=timestamp.desc&limit=500')]);indicator('cloud-indicator',true,'Supabase');allEvents=events;renderStatus(statuses[0]);renderEvents(events.slice(0,100));analytics(events)}catch(error){indicator('cloud-indicator',false,'Supabase');$('edge-message').textContent=error.message.includes('401')?'Telemetry is private. A specific Supabase viewer must be authorized before browser access is enabled.':'Cloud data is temporarily unavailable.';toast('Cloud telemetry is restricted')}}
function toast(message){const t=$('toast');t.textContent=message;t.classList.add('show');setTimeout(()=>t.classList.remove('show'),2500)}
$('apply-filter').onclick=()=>{const status=$('event-status').value,start=$('event-start').value?new Date($('event-start').value):null,end=$('event-end').value?new Date($('event-end').value):null;renderEvents(allEvents.filter(e=>(!status||e.status===status)&&(!start||new Date(e.timestamp)>=start)&&(!end||new Date(e.timestamp)<=end)).slice(0,100))};
setInterval(()=>$('clock').textContent=new Date().toLocaleString(),1000);setInterval(refresh,3000);refresh();
